# Managed by repository-settings/app
# https://github.com/repository-settings/app

repository:
  description: "Differentiable operators for discrete structure"
  homepage: "https://docs.rs/structops"
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

  topics:
    - differentiable-programming
    - dynamic-programming
    - machine-learning
    - rust
    - structured-prediction
